name: SmartParking

dependencies:
  - nodejs
  - python
  - numpy
  - requests
  - pip
  - pip:
    - tb-mqtt-client
    - tb-rest-client
    - psycopg2
    - django
    - folium
    - matplotlib
    - opencv-python
    - django-sslserver
    - django-tailwind
    - django-compressor