# Generated by Django 4.1.5 on 2023-01-27 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='id',
        ),
        migrations.RemoveField(
            model_name='user',
            name='plate',
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=7, primary_key=True, serialize=False),
        ),
    ]
