# Generated by Django 4.1.5 on 2023-02-03 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parkings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='price',
            name='day',
            field=models.CharField(max_length=14, null=True),
        ),
    ]
