# Generated by Django 4.1.5 on 2023-01-31 02:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parkings', '0002_rename_user_stop_user_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stop',
            old_name='user_id',
            new_name='user',
        ),
    ]
