# Generated by Django 4.1.5 on 2023-02-18 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parkings', '0003_alter_price_day'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stop',
            name='start_time',
            field=models.DateTimeField(),
        ),
    ]
