# Generated by Django 4.1.5 on 2023-01-27 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parkings', '0003_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Price',
            fields=[
                ('price_id', models.AutoField(primary_key=True, serialize=False)),
                ('park', models.CharField(max_length=50)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('date', models.DateField(null=True)),
                ('day', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Statistic',
            fields=[
                ('statistic_id', models.AutoField(primary_key=True, serialize=False)),
                ('park', models.CharField(max_length=50)),
                ('total_income', models.DecimalField(decimal_places=2, max_digits=5)),
                ('total_stops', models.IntegerField()),
                ('total_active_stops', models.IntegerField()),
                ('date', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.RenameField(
            model_name='payment',
            old_name='stop_id',
            new_name='stop',
        ),
        migrations.AddField(
            model_name='stop',
            name='park',
            field=models.CharField(default='a', max_length=50),
            preserve_default=False,
        ),
    ]
