# Generated by Django 4.1.5 on 2023-01-28 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parkings', '0006_alter_stop_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stop',
            name='user',
            field=models.CharField(max_length=50),
        ),
    ]
