# Generated by Django 4.1.5 on 2023-01-28 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parkings', '0009_rename_total_active_stops_statistic_active_stops_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='statistic',
            old_name='complete_stops',
            new_name='completed_stops',
        ),
    ]
