# Generated by Django 4.1.5 on 2023-01-29 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parkings', '0011_alter_statistic_average_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statistic',
            name='average_time',
            field=models.TimeField(),
        ),
    ]
