# Generated by Django 4.1.5 on 2023-01-29 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parkings', '0012_alter_statistic_average_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statistic',
            name='average_time',
            field=models.DurationField(),
        ),
    ]
