# Generated by Django 4.1.5 on 2023-01-30 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parkings', '0013_alter_statistic_average_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='price',
            name='end_time',
            field=models.TimeField(default='23:59:59'),
        ),
        migrations.AlterField(
            model_name='price',
            name='start_time',
            field=models.TimeField(default='00:00:00'),
        ),
    ]
