# Generated by Django 4.1.4 on 2022-12-22 19:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('stops', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stop',
            name='end',
        ),
        migrations.RemoveField(
            model_name='stop',
            name='start',
        ),
        migrations.AddField(
            model_name='stop',
            name='end_time',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='stop',
            name='start_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='stop',
            name='plate',
            field=models.CharField(max_length=8),
        ),
        migrations.AlterField(
            model_name='stop',
            name='stop_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
