# Generated by Django 4.1.4 on 2022-12-23 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stops', '0002_remove_stop_end_remove_stop_start_stop_end_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stop',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
    ]
