# Generated by Django 4.1.4 on 2022-12-23 20:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stops', '0003_stop_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('payment_id', models.AutoField(primary_key=True, serialize=False)),
                ('payment_time', models.DateTimeField(auto_now_add=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=5)),
                ('stop_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stops.stop')),
            ],
        ),
    ]
