# Generated by Django 4.1.5 on 2023-01-26 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FilterModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('smartparks', models.CharField(max_length=10)),
                ('start_date', models.DateField(max_length=8)),
                ('end_date', models.DateField(max_length=8)),
                ('username', models.CharField(max_length=100)),
                ('plate', models.CharField(max_length=10)),
            ],
        ),
    ]
