# Generated by Django 4.1.5 on 2023-01-31 01:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FilterModel',
        ),
    ]
